# Generated by Django 2.2.4 on 2020-10-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_lick',
            new_name='restaurant_link',
        ),
    ]
